name: PHP-Prefixer
author: PHP Prefixer <team@php-prefixer.com>
description: 'Prefix PHP libraries and projects. PHP-Prefixer is a service to apply vendor prefixes to Composer namespaces, traits & more.'

inputs:
  personal_access_token:
    description: 'The PHP-Prefixer PAT/Personal Access Token. The token must be configured in the PHP-Prefixer account. Example: `789|1234567890123456789012345678901234567890`.'
    required: true

  project_id:
    description: 'The project ID to process the source code. The project must be configured in your account in the PHP-Prefixer account. Example: `5123`.'
    required: true

  source_dir_path:
    description: 'The relative path to the source project directory. It must contain a .git repository and composer.json file. If not, set the base repository directory will be used as the value. Example: `foo/bar`.'
    required: false

  target_branch:
    description: 'The branch in the repository where PHP-Prefixer will store the prefixed files after processing. By default: `prefixed`.'
    required: false
    default: 'prefixed'

  gh_personal_access_token:
    description: 'The GitHub PAT/Personal Access Token to access private repositories. It is only required if the project, the library or the dependencies are private.'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'blue'
